; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    https://github.com/erodarob/RadioMessage.git
    sparkfun/SparkFun u-blox GNSS v3@^3.1.13
build_src_filter =
    +<*>
    -<SDLog.cpp>
    
    -<TerminalPrint.cpp>
    -<RecordData/DataLoggingSupporterClasses/FileLog/>
    -<RecordData/Retrieval/>


[env:native]
platform = native
build_flags =
    -D NATIVE=1
    -D NATIVE_NO_STDOUT_DATA=1
build_src_filter =
    +<*>
    -<Sensors/>
    -<RecordData/DataLoggingSupporterClasses/FileLog/>
    -<RecordData/DataLoggingSupporterClasses/UARTLog/>
    -<RecordData/DataLoggingSupporterClasses/USBLog/>
    -<RecordData/Retrieval/>
